version: '3.1'
services:
  mongo-container:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test@123
    ports:
      - "27017:27017"
    command: mongod